### ISSUE TITLE
Game freezes upon clicking "World Preview" in game menu. [1.20.1]

### ISSUE THREAD

**Issue by Arrowpuppet** [caeruleusDraconis/world-preview#25]
### What happened?

Tested on both Fabric 0.15.7 and Quilt 0.23.1 with no other mods.

The main preview while creating a world works just fine, but the in-world preview reliably causes the game to freeze (but not crash).

### Minecraft Version

1.20.1

### Modloader (Fabric/Forge)

Fabric/Quilt

### World-Preview Version

1.2.0

### Minecraft Logs

```[14:57:13] [Render thread/INFO]: [STDERR]: java.util.concurrent.CompletionException: java.nio.file.InvalidPathException: Illegal char <:> at index 9: minecraft:overworld-8-87553.zip
[14:57:13] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:156)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:130)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_1255.method_5383(class_1255.java:115)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1175)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:802)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:250)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
[14:57:13] [Render thread/INFO]: [STDERR]: Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 9: minecraft:overworld-8-87553.zip
[14:57:13] [Render thread/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at java.base/java.nio.file.Path.resolve(Path.java:515)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at caeruleusTait.world.preview.client.gui.screens.InGamePreviewScreen.loadPreviewStorage(InGamePreviewScreen.java:115)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at caeruleusTait.world.preview.backend.WorkManager.postChangeWorldGenState(WorkManager.java:138)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at caeruleusTait.world.preview.client.gui.screens.PreviewContainer.updateSettings_real(PreviewContainer.java:470)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at caeruleusTait.world.preview.client.gui.screens.PreviewContainer.lambda$updateSettings$21(PreviewContainer.java:355)
[14:57:13] [Render thread/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[14:57:13] [Render thread/INFO]: [STDERR]: 	... 14 more```

**Comment by caeruleusDraconis** [comment]
Thanks for reporting. Should be fixed with the [1.2.1](https://modrinth.com/mod/world-preview/version/lSCY5eo1) version.
