### ISSUE TITLE
This save of the exisiting world preview causing crashes.

### ISSUE THREAD

**Issue by frosthuuund** [caeruleusDraconis/world-preview#34]
### What happened?

The game just hangs on initializing preview screen.

### Minecraft Version

1.20.4

### Modloader (Fabric/Forge)

Fabric

### World-Preview Version

1.1.5

### Minecraft Logs

```
[06:16:04] [Render thread/INFO]: [STDOUT]: net.minecraft.class_433
[06:16:04] [Server thread/INFO]: Saving and pausing game...
[06:16:04] [Server thread/INFO]: Saving chunks for level 'ServerLevel[terradip]'/minecraft:overworld
[06:16:04] [Server thread/INFO]: Saving chunks for level 'ServerLevel[terradip]'/minecraft:the_end
[06:16:04] [Server thread/INFO]: Saving chunks for level 'ServerLevel[terradip]'/minecraft:the_nether
[06:16:05] [Render thread/INFO]: [STDOUT]: caeruleusTait.world.preview.client.gui.screens.InGamePreviewScreen
[06:16:05] [Render thread/INFO]: Start generating biome data...
[06:16:05] [Render thread/INFO]: [STDOUT]: caeruleusTait.world.preview.client.gui.screens.PreviewCacheLoadingScreen
[06:16:05] [Render thread/INFO]: Reading preview data from C:\Users\user\AppData\Roaming\PrismLauncher\instances\1.20.4\.minecraft\saves\terradip\.\world-preview\minecraft_overworld-8-87553.zip
[06:16:05] [Render thread/INFO]: [STDOUT]: caeruleusTait.world.preview.client.gui.screens.InGamePreviewScreen
[06:16:05] [Render thread/WARN]: No color mapping for 9 biomes found. The list of biomes without a color mapping can be found in C:\Users\user\AppData\Roaming\PrismLauncher\instances\1.20.4\.minecraft\config\world_preview\missing-colors.json
[06:16:05] [Render thread/WARN]: No structure data for 2 structure found. The list of structures without data can be found in C:\Users\user\AppData\Roaming\PrismLauncher\instances\1.20.4\.minecraft\config\world_preview\missing-structures.json
[06:16:05] [pool-30-thread-1/INFO]: Queued 3455 chunks for generation using 432 batches [14 ms] 
[06:16:06] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:940) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1327) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 203 out of bounds for length 174
	at caeruleusTait.world.preview.client.gui.widgets.PreviewDisplay.updateTexture(PreviewDisplay.java:426) ~[world_preview-fabric-1.20.4-1.2.2.jar:?]
	at caeruleusTait.world.preview.client.gui.widgets.PreviewDisplay.method_48579(PreviewDisplay.java:241) ~[world_preview-fabric-1.20.4-1.2.2.jar:?]
	at net.minecraft.class_339.method_25394(class_339.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25394(class_437.java:121) ~[client-intermediary.jar:?]
	at caeruleusTait.world.preview.client.gui.screens.InGamePreviewScreen.method_25394(InGamePreviewScreen.java:73) ~[world_preview-fabric-1.20.4-1.2.2.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.mixinextras$bridge$method_47413$201(class_757.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.wrapOperation$bdb000$fabric-screen-api-v1$onRenderScreen(class_757.java:2111) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:931) ~[client-intermediary.jar:?]
	... 9 more
[06:16:07] [Server thread/INFO]: Stopping server
[06:16:07] [Server thread/INFO]: Saving players
[06:16:07] [Server thread/INFO]: Saving worlds
```

### Additional Information

[-1963069003-minecraft_overworld-4-87553.zip](https://github.com/user-attachments/files/15509190/-1963069003-minecraft_overworld-4-87553.zip)

**Comment by frosthuuund** [comment]
Nevermind, its turned out its not world cache

**Comment by caeruleusDraconis** [comment]
Version `1.1.5` is not the latest version and also has a different known issue #20. Could you please try Version `1.2.2`?
